title: Khoerodin
tagline: Developer, writer, and maker
description: Passionate Ruby on Rails web developer since 2018 based in Indonesia, specializing in robust applications. Thrives on pushing boundaries, delivering high-quality code and seamless user experiences. Let's create something exceptional together.
url: https://khoerodin.id
permalink: /:title

author:
  name: Khoerodin
  url: https://khoerodin.id
  email: khoerodin@live.com
  twitter: khoerodin

plugins:
  - jekyll-redirect-from

theme: jekyll-theme-productive
google_analytics: UA-91739383-1

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
