name                : Khoerodin
description         : Bismillah, Berkah, Manfaat
meta_description    : "Khoerodin's blog"


markdown            : kramdown
highlighter         : rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

paginate            : 5
paginate_path       : /page/:num
baseurl             : 
domain_name         : 'http://khoerodin.id'
google_analytics    : '#'
disqus_shortname    : 'khoerodin'

# Details for the RSS feed generator
url                 : 'http://khoerodin.id'
author              : 'Khoerodin'

permalink           : /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

gems:  
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag