title               : 'Khoerodin'
description         : 'Bebsite-blog yang ditulis Khoerodin, seorang web developer dengan pengalaman lebih dari 3 tahun. Website ini memuat materi web-development mulai dari dasar sampai tahap deployment ke server.'
short_description   : 'Web Developer, Writer and Maker'
lang                : id
email               : khoerodin@live.com
author              :
  khoerodin         :
    twitter         : khoerodin
    facebook        : khoerodin

twitter             : khoerodin
facebook            : khoerodin
linkedin            : khoerodin

google_analytics    : 'UA-91739383-1'
disqus              : 'khoerodin'

markdown            : kramdown
highlighter         : rouge
# https://github.com/jekyll/jekyll/issues/4619
kramdown:
  # use Github Flavored Markdown
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true
  # do not replace newlines by <br>s
  hard_wrap: false

# https://github.com/oncleben31/jekyll-date-basic-i18n
date_format         : '%-d %B %Y'

# Details for the RSS feed generator
url                 : 'https://khoerodin.id'
permalink           : /blog/:title/

collections:
  object-oriented-php:
    output: true
    permalink: /object-oriented-php/:path/
    label: 'object-oriented-php' # dipake di home, dan skill page
    title: 'Object-Oriented PHP' # dipake di home, dan skill page
    skill: php #dipake di home, dan skill page
    level: intermediate #dipake di skill page

  others:
    output: true
    permalink: /others/:path/

defaults:
    -
      scope:
        path: ""
        type: pages
      values:
        layout: default
    -
      scope:
        path: ""
        type: posts
      values:
        layout: post

# jekyll-archives
jekyll-archives:
  enabled: ['tags']
  layout: 'tagar'
  permalinks:
    tag: '/blog/tagar/:name/'

pagination:
  enabled: true


gems:
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-archives
  - jekyll-paginate-v2
  
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - gulpfile.js
  - package.json
  - todo-tugas.todo
  - node_modules