title: Khoerodin
url: https://khoerodin.id
permalink: /:title

author:
  name: Khoerodin
  url: https://khoerodin.id
  domain: khoerodin.id
  email: khoerodin@live.com
  github: khoerodin
  twitter: khoerodin

plugins:
  - jekyll-redirect-from

theme: jekyll-theme-productive
google_analytics: UA-91739383-1

defaults:
  - values:
      locale: en

  # posts
  - scope:
      path: _posts/id/**
      type: posts
    values:
      locale: id
      permalink: /id/:title

  # static pages
  - scope:
      path: _pages/id/**
      type: pages # collection named "pages"
    values:
      locale: id
      permalink: /id/:title

# for _pages folder
collections:
  pages:
    output: true
    permalink: /:title

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
